/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/my': typeof AuthenticatedMyRoute
  '/new': typeof AuthenticatedNewRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/listings/$id': typeof ListingsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/my': typeof AuthenticatedMyRoute
  '/new': typeof AuthenticatedNewRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/listings/$id': typeof ListingsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/listings/$id': typeof ListingsIdRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/messages'
    | '/my'
    | '/new'
    | '/verify'
    | '/category/$slug'
    | '/listings/$id'
    | '/messages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/messages'
    | '/my'
    | '/new'
    | '/verify'
    | '/category/$slug'
    | '/listings/$id'
    | '/messages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/_authenticated/messages'
    | '/_authenticated/my'
    | '/_authenticated/new'
    | '/_authenticated/verify'
    | '/category/$slug'
    | '/listings/$id'
    | '/_authenticated/messages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  HowItWorksRoute: typeof HowItWorksRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedMyRoute: AuthenticatedMyRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  HowItWorksRoute: HowItWorksRoute,
  CategorySlugRoute: CategorySlugRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
